### ISSUE TITLE
OpenRoast on El Capitan?

### ISSUE THREAD

**Issue by tinyogre** [Roastero/Openroast#43] opened 2016-03-26 17:37 UTC
Last time I tried to upgrade to El Capitan, I had to revert to Yosemite specifically because of the USB driver signing issue with El Capitan.  This looks like it might be a workaround: https://tzapu.com/making-ch340-ch341-serial-adapters-work-under-el-capitan-os-x/

Has anyone tried it with OpenRoast and El Capitan yet?  It's just a new way to disable driver signing, which we always had to do in Yosemite anyway, so maybe it works?

**Comment by lodge93** [comment] 2016-03-26 18:58
I am using the drivers included with the [current release](https://github.com/Roastero/Openroast/releases/latest) under El Capitan (10.11.2) and they are signed. However, I am using a MacBook Pro (13-inch, Mid 2012) and have noticed issues on newer Macbooks. 

I have narrowed the issue down to something with how the roaster uses the USB specification. I believe the roaster requires power from the USB to fully power the internal arduino. If there is not enough power, the on board arduino power cycles and therefore has issues communicating with Openroast. I believe the newer Macbooks follow the USB specification more tightly and only allow more power to be applied if it is asked for specifically, while the roaster does not ask for the power it needs appropriately. I have had limited success with a powered USB hub as a work around.

**Comment by tinyogre** [comment] 2016-03-26 19:29
I see.  My personal laptop is a mid-2012 MBP as well.  But I realized I'm going to have a brand new one from work in a few weeks, I'll see if I can't get set up on it and test it out with my roaster before I try updating mine again.

Alternately, does just running a Linux or Windows VM and giving it access to the USB ports work?  Or does that still have the power issue?  That's actually how I ran the vendor supplied software before Roastero came along anyway.

**Comment by lodge93** [comment] 2016-03-26 19:39
I personally have never had issues in Windows or Linux VMs, but I don't think I ever tried running a vm on a base machine that had issues with Openroast. Let me know how it works out!

**Comment by monbaza** [comment] 2016-05-03 14:19
OpenRoast crashes under El Captain 10.11.4.
I use the driver and the OpenRoast at here: https://github.com/Roastero/Openroast/releases/tag/v1.0.1
The driver installation takes a bit long but it finally finished on a 'restart computer' button.
So I hit it and restart my Macbook Pro 17 inch.
And then I checked if the driver works using the method that comes with the driver.zip.
It all seems OK.
But as soon as I double click OpenRoast from my desktop area, it crashes on a dialog window that describes the error message of the scripts.

**Comment by cmcconomy** [comment] 2017-01-04 13:33
I've installed the patched kext file from http://www.mblock.cc/posts/run-makeblock-ch340-ch341-on-mac-os-sierra which stopped the mac from crashing when I plug in the SR700, but I have a host of new problems:

* the timer isn't counting in seconds. sometimes it counts 2 seconds at a time, other times 1.3 or 1.4 seconds. Screws with the profile times
* unable to start a "cooling" phase. The button doesn't do anything.

I'm thinking of trying to run the SR700 software through WINE instead

**Comment by int3ll3ct** [comment] 2017-03-29 01:09
The QinHeng CH34x V1.4 drivers, the installer of which is included in Openroast v1.2.0a7, worked for me for Yosemite and Sierra - can't personally check on El Capitan.  May be worth a try.

**Comment by monbaza** [comment] 2017-03-29 01:10
Wine? Sounds solid.
I'll try too
Thanks for the hint.

Monbaza
int3ll3ct <notifications@github.com>於 2017年3月29日 週三，上午9:09寫道：

**Comment by cmcconomy** [comment] 2017-03-29 11:46
@monbaza I found the issue was related to my macbook's use of USB3 ports. When I connected the SR700 through a USB2 hub, it worked correctly.

**Comment by int3ll3ct** [comment] 2017-03-29 13:08
My Dell laptop has the same issue - it doesn't work on the USB3 port, but works on the USB2 port.  I will close this and put a mention of this in future documentation.

**Closed by int3ll3ct** 2017-03-29 13:08 UTC
Labels: question

**Comment by monbaza** [comment] 2017-03-29 16:07
https://github.com/Roastero/Openroast/releases
Cant wait to test!
Thank you int3II3ct  !

2017-03-29 21:08 GMT+08:00 int3ll3ct <notifications@github.com>:

**Comment by monbaza** [comment] 2017-03-30 05:56
works here!  OSX 10.12.3 Sierra
on
El Salvador Miel de Rosa honey
Quiet after 1c finished.
I'd love to pay for this software!

2017-03-30 0:07 GMT+08:00 monbaza <monbaza@gmail.com>:

**Comment by int3ll3ct** [comment] 2017-03-30 12:41
Thanks for the update. Glad to hear it's working for you!

**Comment by monbaza** [comment] 2017-04-14 01:15
I have a doubt of the temperature reading from SR700.
Can OpenRoast read a USB feed from a thermometer? I suppose there are a few
thermometer that has a Probe and a USB. The probe can be installed into the
chamber for temperature detection. The USB is a data delivery from the
thermometer to my MacBook Pro.

Cheers,

Monbaza

int3ll3ct <notifications@github.com>於 2017年3月30日 週四，下午8:41寫道：

> Thanks for the update. Glad to hear it's working for you!
>

**Comment by int3ll3ct** [comment] 2017-04-15 20:55
@monbaza, in my opinion, putting features in Openroast that would reproduce what Artisan already offers would not be an effective use of time and energy.  I am separately working on an Artisan plug-in for the SR700, but that will require specific hardware and is a few months away yet.  So I don't plan on adding this feature to Openroast at this time, although someone else may come along at some point who decides they want to do it.

The temperature reading on the SR700 comes from a thermocouple in the base of the unit, below the beans.  It is not a bean temperature (BT) reading nor really an environment temperature (ET) reading, because BT is typically measured in the bean mass and ET is typically meaured downstream from the beans, in the exhaust path (that's my understanding, anyway...).  But IMO the SR700 temperature reading is at least a reasonable approximation for ET, even though it's measured upstream from the bean mass.

**Comment by monbaza** [comment] 2017-04-16 12:24
Hi int3ll3ct,

No problem mate.
It is already good as it is!
I understand the BT does not follow the rising curve of the heating unit of
SR 700. I have always inserted a probe into the chamber for a temperature
reading.
Playing along with SR 700 with OpenRoast is so much fun and sometime even
scientific to me.

Cheers and thank you very much!

Monbaza

int3ll3ct <notifications@github.com>於 2017年4月16日 週日，上午4:55寫道：
